# 4 node (3 workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-homelab-cluster
networking: 
  apiServerAddress: "127.0.0.1"
  apiServerPort: 8889 # This specifies the port *inside* the control plane container if you omit extraPortMappings.
                      # However, with extraPortMappings, it's about what the control plane *thinks* its accessible port is.
                      # For clarity, let's keep extraPortMappings for the host exposure.
nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  extraPortMappings:
  - containerPort: 6443
    hostPort: 8889
    listenAddress: "127.0.0.1" # Listen on localhost, or "0.0.0.0" for all interfaces
    protocol: TCP
- role: worker
  image: kindest/node:v1.28.0
- role: worker
  image: kindest/node:v1.28.0